### ISSUE TITLE
Update stack breaks

### ISSUE THREAD

**Issue by NaraGitHub** [maciejtreder/serverless-apigw-binary#1]
Works great during createStack (first time).  Later if add new binary Media type - breaks 

Create stack:
========
custom:
  apigwBinary:
    types:
      - 'application/json'

update stack
=====
custom:
  apigwBinary:
    types:
      - 'application/json'
      - 'application/text'

**Comment by maciejtreder** [comment]
Thank you for report. Bug should not occur anymore. Please verify.

**Comment by NaraGitHub** [comment]
Hangs after deploying function .  

 Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.11.0
     Serverless Version: 1.10.1

Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (6.47 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..........................
Serverless: Stack update finished...
Serverless: Removing old service versions...
Service Information
service: NoteApi
stage: devgzip
region: us-east-1
api keys:
  None
endpoints:
  GET - https://ZZZZZZ.execute-api.us-east-1.amazonaws.com/devgzip/notes
  POST - https://ZZZZZZexecute-api.us-east-1.amazonaws.com/devgzip/notes
functions:
  findNotes: XXXXXX-devgzip-findNotes
  saveNote: XXXXXX-devgzip-saveNote
^CTerminate batch job (Y/N)? y

**Comment by maciejtreder** [comment]
Let's track this problem here: #6
