### ISSUE TITLE
Is this plugin dependable of aws-serverless-express?

### ISSUE THREAD

**Issue by rcfrias** [maciejtreder/serverless-apigw-binary#11]
I've noticed that the examples are using the "aws-serverless-express" server, what for me its too much overhead, so I want to only support image/jpeg and manipulate it inside my lambda with something like Graphics Magick and thats it, no need to have a universal entry point.
*Btw, have you tried sending data + image with multipart/form-data using this plugin and succeeded?

**Comment by maciejtreder** [comment]
Hello,

This plugin doesn't depend on aws-serverless-express. This library is used only as an example of usage.


No I did not try to send image via multipart/form with this plugin.
