### ISSUE TITLE
Serverless plugin "serverless-apigw-binary" not found

### ISSUE THREAD

**Issue by eraserfusion** [maciejtreder/serverless-apigw-binary#27]
https://github.com/maciejtreder/serverless-apigw-binary/blob/ce06a5c386082bc8756122285300f943ac44887c/src/index.js#L1

I have an environment with an older version of node that is not loading this plugin. Digging a little deeper, the only issue is that `'use strict';` is **not** at the top of the file. When I add it in locally everything deploys as expected.

**Comment by maciejtreder** [comment]
@eraserfusion Thank you for this report. Could you verify newest version (0.4.1)?

**Comment by ethanherbertson** [comment]
I sit right next to @eraserfusion in meatspace, and can confirm that 0.4.1 has fixed his (and my) problem.

Thank you once again for the quick fix!

**Comment by maciejtreder** [comment]
Sounds great. Thanks!
