### ISSUE TITLE
Externalized environment configuration support

### ISSUE THREAD

**Issue by kennyw12** [maciejtreder/serverless-apigw-binary#36]
Serverless blows up with `Serverless plugin "serverless-apigw-binary" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.` when I try to use externalized env files. 

```
custom: ${file(environment/${self:provider.stage}.json)}
```

It seems like this [line](https://github.com/maciejtreder/serverless-apigw-binary/blob/master/src/index.js#L7) is the culprit. BinarySupport is initialized trying to read from the yml but serverless has not populated the custom key yet. Moving this inline to its usage solves this issue.

**Comment by maciejtreder** [comment]
Hello @kennyw12 Please verify your bugfix in the latest release (0.4.3).

Thanks in advance!

**Comment by kennyw12** [comment]
Hi @maciejtreder It doesn't seem like the changes in my PR are in 0.4.3.

https://registry.npmjs.org/serverless-apigw-binary/-/serverless-apigw-binary-0.4.3.tgz

**Comment by maciejtreder** [comment]
@kennyw12  You're right! Check out now (0.4.4)

**Comment by kennyw12** [comment]
@maciejtreder Thanks!

**Comment by maciejtreder** [comment]
Thank you for your input 👍
