### ISSUE TITLE
Serverless: 'Too many requests' received, sleeping 5 seconds

### ISSUE THREAD

**Issue by centosGit** [maciejtreder/serverless-apigw-binary#42]
Not much of feedback to give you but noticed this message whenever i make use of your plugin.

```
Serverless: 'Too many requests' received, sleeping 5 seconds
Serverless: 'Too many requests' received, sleeping 5 seconds
```

If i remove the plugin i do not get the message any more.

**Comment by maciejtreder** [comment]
This is expected behavior. AWS doesn't allow to perform multiple requests at one time. After setting up an API Gateway, plugin needs to send another request to set up binaryData.
