### ISSUE TITLE
Hangs after deploying function

### ISSUE THREAD

**Issue by maciejtreder** [maciejtreder/serverless-apigw-binary#6]
Hangs after deploying function .  (tried "serverless-apigw-binary": "^0.3.4") 

 Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.11.0
     Serverless Version: 1.10.1

Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (6.47 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..........................
Serverless: Stack update finished...
Serverless: Removing old service versions...
Service Information
service: NoteApi
stage: devgzip
region: us-east-1
api keys:
  None
endpoints:
  GET - https://ZZZZZZ.execute-api.us-east-1.amazonaws.com/devgzip/notes
  POST - https://ZZZZZZexecute-api.us-east-1.amazonaws.com/devgzip/notes
functions:
  findNotes: XXXXXX-devgzip-findNotes
  saveNote: XXXXXX-devgzip-saveNote
^CTerminate batch job (Y/N)? y

**Comment by NaraGitHub** [comment]
do you have any update? Thanks

**Comment by maciejtreder** [comment]
Hello,

Unfornatelly I was unable to reproduce your issue.

As far as I can see from your logs, you got output from `serverless deploy`. What about binary settings? Was there applied to your API gateway, or the whole process have hanged out before that?
